#!/bin/bash -e

echo "[malvarma] Running Malvarma."
echo "[malvarma] Installing rng-tools (ignore any rng-tools.service errors)"

dpkg -i /rng-tools_2-unofficial-mt.14-1_armhf.deb &> /dev/null

echo "[malvarma] Testing available entropy..."

if python /test_entropy.py ; then
    echo "[malvarma] FIPS 140-2 test passed. Good."
    echo "[malvarma] Generating cold wallet..."

    python /py2-monero-wallet-generator/gen_wallet.py --clear

    echo "[malvarma] You may now destroy this device and SD card. Visit https://github.com/weijiekoh/malvarma for instructions."
else
    echo "[malvarma] FIPS 140-2 failure rate: more than 5 / 1000. Not good."
    echo "[malvarma] This sytem has insufficient entropy, and may not generate a sufficiently secure cold wallet. Restart this device to try again."
fi

exit 0
